@baseURL = http://localhost:3333

###
# @name create_org
@email = johndoe@example.com
@password = 123123123
POST {{baseURL}}/orgs
Content-Type: application/json

{
  "name": "John Doe",
  "email": "{{email}}",
  "password": "{{password}}",
  "cep": "12345678",
  "address": "Rua John Doe",
  "city": "John Doe",
  "state": "John Doe",
  "phone_number": "11900001111"
}

###
# @name authenticate_org
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name refresh_token
# @refresh = {{refresh_token.response.headers.set-cookie}}
@token = {{refresh_token.response.body.token}}
@refresh = {{authenticate_org.response.headers.set-cookie}}
# @token = {{authenticate_org.response.body.token}}

PATCH {{baseURL}}/token/refresh
Cookie: {{refresh}}

###
# @name upload_pet_pictures

POST {{baseURL}}/pets/pictures/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="pet1.png"
Content-Type: image/png

< ./pet.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="pet2.png"
Content-Type: image/png

< ./pet.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# @name create_pet

POST {{baseURL}}/pets
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe Pet",
  "about": "John Doe Pet",
  "age": "PUPPY",
  "size": "SMALL",
  "energy": "VERY_LOW",
  "independence": "LOW",
  "environment": "John Doe Pet",
  "adoptionRequirements": [
    "John Doe Pet",
    "John Doe Pet"
  ],
  "petPictures": [
    "{{upload_pet_pictures.response.body.files[0].url}}",
    "{{upload_pet_pictures.response.body.files[1].url}}"
  ]
}